### ISSUE TITLE
Unable to enter text after selecting 'Enable Custom'

### ISSUE THREAD

**Issue by AQuartley** [Tony905x/pet-to-npc-transmog#3]
When selecting 'Enable Custom' I am unable to add text in any of the fields provided, even attempting to force paste doesn't work.

Is this currently known/intended?

![petplugin](https://github.com/user-attachments/assets/af4a54ea-7892-476e-b186-116d8ff45041)

Thanks

**Comment by Tony905x** [comment]
Ya this is a bug that was pointed out to me, I'm working on it now.  It's caused when there isn't any saved data yet on the account.  So pretty much anyone who just downloaded the plugin, I missed this in my testing because I had a ton of my own data in there.  It will be an easy fix but unsure when runelite team will push it live, hopefully not too long.

**Comment by killa-goose** [comment]
Any chance you can share the config storage location and an example saved config or the format so we can put something there to enable us to create our own in the meantime while we wait for the plugin update?

**Comment by Tony905x** [comment]
unfortunately it gets saved to a jagex managed system, so you wouldn't be able to alter it
